# 线上配置文件
server:
  port: 8090
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9yh8134rse19ed9zo.mysql.rds.aliyuncs.com:3306/source_website
    username: root
    password: cC15179725977
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 47.107.29.107
    port: 6379
    timeout: 5000
    password: 123456
    lettuce:
      pool:
        max-active: 8 #最大空闲连接数默认8
        max-idle: 8 #最大连接数
        max-wait: 100ms #最大等待时间
        min-idle: 0 #最小连接数
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''