spring:
  # session 配置
  session:
    #  开启分布式 session（须先配置 Redis）
    store-type: redis
    #     30 天过期
    timeout: 2592000
    path: /api
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/source_website?rewriteBatchedStatements=true
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: api-service
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
server:
  port: 8092
  servlet:
    context-path: /api/API
#api:
#  client:
#    secret-key: 12345678
#    access-key: admin
knife4j:
  enable: true