server:
  port: 8093
  servlet:
    context-path: /api/API
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8091 #api真实ip
          predicates:
            - Path=/**
    nacos:
      server-addr: localhost:8848
  application:
    name: api-gateway