server:
  port: 8093
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8888
          predicates:
            - Path=/user/*
        - id: path_route
          uri: http://localhost:8091
          predicates:
           - Path=/sandbox/*